[PERMISSIONS-SUPPORT] :sparkles: Add support for maintain and triage …
mineiros-io/terraform-github-team pull request #38
Opened 2021-06-02 17:42 UTC by PavelSusloparov

…repositories permissions

2021-06-02 21:14 UTC, soerenmartius requested changes
Hey Pavel!

Thanks for your contribution. We appreciate that!
I've found one bug that needs to be fixed before we can get this merged. Also, @mariux , could you review this PR also, please?

Thanks and best regards,
Soren

2021-06-02 21:14 UTC, soerenmartius commented on main.tf
> +  repositories = merge(local.repo_admin, local.repo_admin, local.repo_push, local.repo_triage, local.repo_pull)
```suggestion
  repositories = merge(local.repo_admin, local.repo_maintain, local.repo_push, local.repo_triage, local.repo_pull)
```

2021-06-02 21:21 UTC, soerenmartius commented
Tests seem to fail because PRs coming from forked repos won't be able to access secrets in CI runs. Will trigger a test run manually once we have the change request applied.

2021-06-02 23:56 UTC, PavelSusloparov commented
Good catch. I addressed the comment.

2021-06-03 08:20 UTC, soerenmartius commented
I've checked out the branch and executed the tests. LGTM!

2021-06-03 08:20 UTC, soerenmartius approved these changes
lgtm!

2021-06-03 08:21 UTC, soerenmartius commented
> lgtm!

@PavelSusloparov will merge later today, edit the CHANGELOG and release.

2021-06-03 08:23 UTC, merged