Add support for Terraform v1
mineiros-io/terraform-github-team pull request #45
Opened 2021-06-28 08:28 UTC by soerenmartius

- feat: add support for Terraform v1
- chore: prepare v0.6.0 release

2021-06-29 19:24 UTC, mariux requested changes
please rebase

2021-06-29 21:22 UTC, soerenmartius commented
> please rebase

rebased from master

2021-07-03 15:15 UTC, soerenmartius commented
ping @mariux

2021-07-06 16:40 UTC, mariux approved these changes
lgtm

2021-07-07 09:08 UTC, merged