mariux/changes
mineiros-io/terraform-github-team pull request #52
Opened 2022-01-02 20:10 UTC by mariux

- chore!: drop inputs from outputs and add docs
- chore!: drop support for broken terraform versions
- feat!: Add support for module_enabled
- feat: Automatically remove maintainers from members to resolve conflicst on the fly
- chore: prepare 0.8.0 release

2022-01-02 21:34 UTC, kassianh submitted a review, later dismissed
lgtm

2022-01-02 22:06 UTC, soerenmartius requested changes

2022-01-02 22:06 UTC, soerenmartius commented on CHANGELOG.md
> +## [0.8.0]
please add scope, 

e.g.

```
## Breaking Change

## Added 
- ...

```

2022-01-03 13:55 UTC, mariux commented on CHANGELOG.md
> +## [0.8.0]
```suggestion
## [0.8.0]

### Added

```

2022-01-03 13:56 UTC, mariux commented on CHANGELOG.md
> +## [0.8.0]
good catch... done.

2022-01-03 14:42 UTC, soerenmartius approved these changes
lgtm

2022-01-03 14:42 UTC, soerenmartius commented on CHANGELOG.md
> +
```suggestion
```

2022-01-03 15:46 UTC, merged